development: &common_settings
  env: 'development'
  app_name: 'City Report Cluj-Napoca'
  base_url: 'http://localhost:3000/'
  allow_delete_all: true
  allow_downvotes: true
  string_max_length:
    name: 32
    comments: 140
    address: 140
  meta:
    categories: ['groapă', 'gunoi', 'vandalism', 'altele']
    zones: [
      'Andrei Mureșanu',
      'Bulgaria',
      'Bună Ziua',
      'Centru',
      'Dâmbul Rotund',
      'Gara',
      'Gheorgheni',
      'Grădini Mănăștur',
      'Grigorescu',
      'Gruia',
      'Hidelve',
      'Iris',
      'Între Lacuri',
      'Mănăștur',
      'Mărăști',
      'Someșeni',
      'Zorilor',
      'Sopor',
      'Borhanci',
      'Becaș',
      'Făget',
      'Zorilor sud (Europa)',
      'Lomb',
      'Tineretului',
      'Pata-Rât'
    ]
  map_center:
    lat: 46.768322
    lon: 23.595002

test:
  <<: *common_settings
  env: 'test'

production:
  <<: *common_settings
  env: 'production'
  base_url: 'http://www.cityreportapp.com/'
  allow_delete_all: true
  allow_downvotes: true
