development: &common_settings
  env: 'development'
  base_url: 'http://localhost:9292/'
  allow_delete_all: true
  allow_downvotes: true
  string_max_length:
    name: 32
    comments: 140
    address: 140
  meta:
    categories: ['groapă', 'gunoi', 'vandalism', 'altele']
    zones: ['Andrei Mureșanu', 'Bulgaria', 'Bună Ziua', 'Centru']

test:
  <<: *common_settings
  allow_downvotes: true
  env: 'test'

production:
  <<: *common_settings
  env: 'production'
  base_url: 'http://192.168.0.15/'
