development: &common_settings
  env: 'development'
  app_name: 'City Report Cluj-Napoca'
  base_email: 'info@cityreportapp.com'
  base_url: 'http://localhost:3000/'
  allow_delete_all: true
  allow_downvotes: true
  show_doc: true
  language:
    default_eula_language: 'ro'
    valid_eula_languages: ['en', 'ro']
  string_max_length:
    name: 32
    comments: 140
    address: 140
  max_distance_validator: true
  max_distance_to_map_center: 1
  map_center:
    lat: 46.768322
    lon: 23.595002
  redis:
    url: 'redis://localhost:6379/12'
    # url: 'redis://172.17.0.4:6379/12'

test:
  <<: *common_settings
  env: 'test'

production:
  <<: *common_settings
  env: 'production'
  base_url: 'http://www.cityreportapp.com/'
  allow_delete_all: false
  allow_downvotes: false
  show_doc: true
  max_distance_validator: false
