development: &common_settings
  env: 'development'
  base_url: 'http://localhost:3000/'
  allow_delete_all: true
  allow_downvotes: true
  string_max_length:
    name: 32
    comments: 140
    address: 140
  meta:
    categories: ['groapă', 'gunoi', 'vandalism', 'altele']
    zones: ['Grigorescu', 'Mănăștur', 'Zorilor', 'Gheorgheni', 'Centru', 'Dâmbul Rotund', 'Iris']
  map_center:
    lat: 46.768322
    lon: 23.595002

test:
  <<: *common_settings
  env: 'test'

production:
  <<: *common_settings
  env: 'production'
  base_url: 'http://192.168.0.15/'
  allow_delete_all: true
  allow_downvotes: true
