development:
  sessions:
    default:
      database: repara-dev
      hosts:
        - localhost:27017
  options:
    raise_not_found_error: false
test:
  sessions:
    default:
      database: repara-test
      hosts:
        - localhost:27017
  options:
    raise_not_found_error: false
production:
  sessions:
    default:
      database: repara-prod
      hosts:
        - localhost:27017
  options:
    raise_not_found_error: false
