development:
  sessions:
    default:
      database: repara-dev
      hosts:
        - localhost:27017
test:
  sessions:
    default:
      database: repara-test
      hosts:
        - localhost:27017
production:
  sessions:
    default:
      database: repara-prod
      hosts:
        - localhost:27017
