# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 8eb5c805192464ca1b56481cd0d6e08ec994f7d020a23c07d4fa86a1acdcd24a94c4938e989c6a7f139a82d85bbc9cc03b0f33232d06ebed0420c1c9b8e2e1be

test:
  secret_key_base: 954f5d68b74ac67c8ca7f3759c742a8d37458243c9db1e9b5acf70a04b4b1c36deb6df5cadaa8950cf68ef2899d5b58db31260448f6c3ff9855a6c914672ff9f

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] || '43d3742050d2e29a7c201f8d5912f5bdbb4de41c7e8633133e961944a924ed3c1668f475b85ec0b3375f10a6da7062d965306a4e1fa92491c95fbf18bbce99a7' %>
